<?php

/**
 * OntoWiki user details template
 *
 * @author Norman Heino <norman.heino@gmail.com>
 * @author Philipp Frischmuth <pfrischmuth@googlemail.com>
 * @version $Id: userdetails.phtml 2917 2009-04-21 12:13:33Z norman.heino $
 */

?>
<fieldset>
    <div>
        <label for="name-input"><?php echo $this->_('Username') ?></label>
        <input class="text" id="name-input" type="text" name="username" <?php echo $this->readonly ?> value="<?php echo $this->username ?>" />
        <br class="clearall" />
    </div>
    <div>
        <label for="email-input"><?php echo $this->_('Email Address') ?></label>
        <input class="text" id="email-input" type="text" name="email" value="<?php echo $this->email ?>" />
        <br class="clearall" />
    </div>
    <div>
        <label for="pw1-input"><?php echo $this->_('Password') ?></label>
        <input class="text" id="pw1-input" type="password" name="password" />
        <br class="clearall" />
    </div>
    <div>
        <label for="pw2-input"><?php echo $this->_('Password (repeat)') ?></label>
        <input class="text" id="pw2-input" type="password" name="password2" />
        <br class="clearall" />
    </div>
    <div style="display:<?php if ($this->currentUser == 'Admin') { echo 'block';} else echo 'None'; ?>"">
	<br class="clearall" />
        <label for="name-input"><?php echo $this->_('I am') ?></label>
        <input id="usertype1" name="usertype" type="radio"  title="Agent" style="width:4%; height:30px;" checked value="Agent" /><label style="width:15%; height:30px; text-align:left">Agent</label>
		<input id="usertype1" name="usertype" type="radio"  title="Datatype" style="width:4%; height:30px " value="Data source" /><label style="width:15%; height:30px; text-align:left">Data source</label>
    </div>
	<div>
		<br class="clearall" />
        <label for="name-input"><?php echo $this->_('Real Name') ?></label>
        <input class="text" id="name-input" type="text" name="realname"  value="<?php echo $this->realName ?>" />
        <br class="clearall" />
    </div>
	<div>
        <label for="name-input"><?php echo $this->_('Institutional Affiliation') ?></label>
        <input class="text" id="name-input" type="text" name="orgAffiliation" value="<?php echo $this->orgAffiliation ?>" />
        <br class="clearall" />
    </div>
	<div>
        <label for="name-input"><?php echo $this->_('Additional Profile Information') ?></label>
        <textarea  style="font-size: 1em;
							line-height: 1.5;
							min-height: 5.5em;
							min-width: 13em;
							padding: 0; width:40.4%" 
				rows="2" cols="20"  name="notes" title ="e.g., specialties or interests"><?php echo $this->notes ?></textarea>
      
    </div>
	<div>
        <label for="name-input"><?php echo $this->_('Website') ?></label>
        <input title="individual or institutional" class="text" id="name-input" type="text" name="website" value="<?php echo $this->website ?>" />
        <br class="clearall" />
    </div>
    
    <!-- UDFR - Abhi - Captcha Additional requirement -->
    <div>
		<br><img id="siimage" style="width:140px; height:40px; " src="<?php echo $this->url ?>extensions/captcha/imagebuilder.php"></img>	
		<a tabindex="-1" style="border-style: none;" href="#" title="Refresh Image" 
	   		onclick="document.getElementById('siimage').src = '<?php echo $this->url ?>extensions/captcha/imagebuilder.php?' + Math.random(); return false;">
	   	<img src="<?php echo $this->url ?>extensions/themes/silverblue/images/refresh.png" alt="Reload Image" onclick="this.blur()" align="bottom" border="0" />
		</a>
		<label for="captcha-input"><?php echo $this->_('Type the code shown')?></label>
		<input class="text" id="captcha-input" MAXLENGTH=8 SIZE=8 name="userstring" type="text" value="">
		<br class="clearall" />
    </div> <!-- Abhi -->
    <div class="clearall"></div>
</fieldset>
