<?php

/**
 * OntoWiki user details template
 *
 * @author Norman Heino <norman.heino@gmail.com>
 * @author Philipp Frischmuth <pfrischmuth@googlemail.com>
 * @version $Id: userdetails.phtml 2917 2009-04-21 12:13:33Z norman.heino $
 */

?>
<div class="messagebox">
	<p style="padding-left:8px">By registering for an account with the UDFR you agree to contribute information under the terms of the Creative Commons 
		<a href="http://creativecommons.org/licenses/by/2.0/">CC-BY</a> license.  
		Furthermore, you agree that your full name, title, institutional affiliation, additional information, and website will be made permanently and publicly visible via the &quot;History&quot; tab for all contributed information.  
		This information is made public in furtherance of the legitimate UDFR business need to provide strong provenance for all content contributions.  For more information refer to the UDFR privacy policy.
	</p>
</div>
<fieldset>
    <div>
        <label for="name-input" title="User name (visible to all users via the History tab)"><?php echo $this->_('Username') ?><span style="color:red">*</span></label>
        <input class="text" id="name-input" type="text" name="username" <?php echo $this->readonly ?> value="<?php echo $this->username ?>" />
        <br class="clearall" />
    </div>
    <div>
        <label for="email-input" title="Email address (visible to UDFR administrators only)"><?php echo $this->_('Email Address') ?><span style="color:red">*</span></label>
        <input class="text" id="email-input" type="text" name="email" value="<?php echo $this->email ?>" />
        <br class="clearall" />
    </div>
    <div>
        <label for="pw1-input" title="Password, minimum of 5 characters (no visibility to anyone)"><?php echo $this->_('Password') ?><span style="color:red">*</span></label>
        <input class="text" id="pw1-input" type="password" name="password" />
        <br class="clearall" />
    </div>
    <div>
        <label for="pw2-input"><?php echo $this->_('Password (repeat)') ?><span style="color:red">*</span></label>
        <input class="text" id="pw2-input" type="password" name="password2" />
        <br class="clearall" />
    </div>
    <div style="display:<?php if ($this->currentUser == 'Admin') { echo 'block';} else echo 'None'; ?>"">
	<br class="clearall" />
        <label for="name-input"><?php echo $this->_('I am') ?></label>
        <input id="usertype1" name="usertype" type="radio"  title="Agent" style="width:4%; height:30px;" checked value="Agent" /><label style="width:15%; height:30px; text-align:left">Agent</label>
		<input id="usertype1" name="usertype" type="radio"  title="Datatype" style="width:4%; height:30px " value="Data source" /><label style="width:15%; height:30px; text-align:left">Data source</label>
    </div>
	<div>
		<br class="clearall" />
        <label for="name-input" title="Full name (visible to UDFR administrators only)" ><?php echo $this->_('Full Name') ?><span style="color:red">*</span></label>
        <input class="text" id="name-input" type="text" name="realname"  value="<?php echo $this->realName ?>" />
        <br class="clearall" />
    </div>
	<div>
        <label for="name-input" title="Job title (visible to all users via the History tab)" ><?php echo $this->_('Title') ?><span style="color:red">*</span></label>
        <input class="text" id="name-input" type="text" name="jobTitle" value="<?php echo $this->jobTitle ?>" />
        <br class="clearall" />
    </div>
	<div>
        <label for="name-input" title="Institutional affiliation (visible to all users via the History tab)" ><?php echo $this->_('Institutional Affiliation') ?><span style="color:red">*</span></label>
        <input class="text" id="name-input" type="text" name="orgAffiliation" value="<?php echo $this->orgAffiliation ?>" />
        <br class="clearall" />
    </div>
	<div>
        <label for="name-input" title="Additional information, e.g., job specialty or expertise (visible to all users via the History tab)">
			<?php echo $this->_('Additional Profile Information') ?>
		</label>
        <textarea  style="font-size: 1em;
							line-height: 1.5;
							min-height: 5.5em;
							min-width: 13em;
							padding: 0; width:40.4%" 
				rows="2" cols="20"  name="notes" title ="e.g., specialties or interests" maxlength="2000"><?php echo $this->notes ?></textarea>
      
    </div>
	<div>
        <label for="name-input" title="Personal or institutional website (visible to all users via the History tab)"><?php echo $this->_('Website') ?></label>
        <input title="individual or institutional" class="text" id="name-input" type="text" name="website" value="<?php echo $this->website ?>" />
        <br class="clearall" />
    </div>
    
    <!-- UDFR - Abhi - Captcha Additional requirement -->
    <div>
		
		<label for="captcha-input"><?php echo $this->_('Type the code shown')?><span style="color:red">*</span></label>
		<input class="text" id="captcha-input" MAXLENGTH=8 SIZE=8 name="userstring" type="text" value="">
		<br>
		<div style="position:relative; margin-left:27%"><img id="siimage" src="<?php echo $this->url ?>extensions/captcha/securimage_show.php"></img>	
		<a tabindex="-1" style="border-style: none;" href="#" title="Refresh Image" 
	   		onclick="document.getElementById('siimage').src = '<?php echo $this->url ?>extensions/captcha/securimage_show.php?' + Math.random(); return false;">
	   	<img src="<?php echo $this->url ?>extensions/themes/silverblue/images/refresh.png" alt="Reload Image" onclick="this.blur()" align="bottom" border="0" />
		</a></div>
    </div> <!-- Abhi -->
    <div class="clearall"></div>
</fieldset>
