<?php

/**
 * OntoWiki user details template
 *
 * @author Norman Heino <norman.heino@gmail.com>
 * @author Philipp Frischmuth <pfrischmuth@googlemail.com>
 * @version $Id: userdetails.phtml 2917 2009-04-21 12:13:33Z norman.heino $
 */

?>
<fieldset>
    <div>
        <label for="name-input"><?php echo $this->_('Username') ?></label>
        <input class="text" id="name-input" type="text" name="username" <?php echo $this->readonly ?> value="<?php echo $this->username ?>" />
        <br class="clearall" />
    </div>
    <div>
        <label for="email-input"><?php echo $this->_('Email Address') ?></label>
        <input class="text" id="email-input" type="text" name="email" value="<?php echo $this->email ?>" />
        <br class="clearall" />
    </div>
    <div>
        <label for="pw1-input"><?php echo $this->_('Password') ?></label>
        <input class="text" id="pw1-input" type="password" name="password" />
        <br class="clearall" />
    </div>
    <div>
        <label for="pw2-input"><?php echo $this->_('Password (repeat)') ?></label>
        <input class="text" id="pw2-input" type="password" name="password2" />
        <br class="clearall" />
    </div>
    
    <!-- UDFR - Abhi - Captcha Additional requirement -->
    <div>
		<br><img id="siimage" style="width:140px; height:40px; " src="<?php echo $this->url ?>extensions/captcha/imagebuilder.php"></img>	
		<a tabindex="-1" style="border-style: none;" href="#" title="Refresh Image" 
	   		onclick="document.getElementById('siimage').src = '<?php echo $this->url ?>extensions/captcha/imagebuilder.php?' + Math.random(); return false;">
	   	<img src="<?php echo $this->url ?>extensions/themes/silverblue/images/refresh.png" alt="Reload Image" onclick="this.blur()" align="bottom" border="0" />
		</a>
		<label for="captcha-input"><?php echo $this->_('Type the code shown')?></label>
		<input class="text" id="captcha-input" MAXLENGTH=8 SIZE=8 name="userstring" type="text" value="">
		<br class="clearall" />
    </div> <!-- Abhi -->
    <div class="clearall"></div>
</fieldset>
