<?php

/**
 * Copyright © 2012 The Regents of the University of California
 *
 * The Unified Digital Format Registry (UDFR) is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

 /**
 * OntoWiki navigation template
 *
 */

#var_dump($this->data);
?>
<!--UDFR - Abhi- Disabled navigation search box <form class="width98">
    <label
        class="display-block onlyAural"
        for="navigation-input">Search in Navigation</label>
    <input
        id="navigation-input"
        class="text width99 inner-label"
        type="text"
        value=""
        name="navigation-input"/>
</form>-->
<div id="navigation-content" class="width99 init-me-please">
<?php 
if( isset($this->stateView) ){
    echo $this->stateView;
} 
?>    
</div>
