<h2>Privacy policy</h2>

<p style="text-align:justify">
The UDFR is operated by the California Digital Library (<a href="http://www.cdlib.org/">CDL</a>) on behalf of the international digital curation community, and adheres to the CDL <a href="http://www.cdlib.org/about/privacy.html">privacy policy</a> and its associated baseline practices.  However, the UDFR has a legitimate business need to provide strong provenance information for all contributed information in order that users can make reasonable determinations of information veracity.  Therefore the names and institutional affiliations of content contributors are permanently and publicly made visible through a link on the &quot;History&quot; tab.
 As required by the CDL policy, this permitted exception to the baseline practices is reviewed annually for continued applicability.

</p>