<?php

/**
 * Copyright © 2012 The Regents of the University of California
 *
 * The Unified Digital Format Registry (UDFR) is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

 ?>
<h2>Privacy policy</h2>

<p style="text-align:justify">
The UDFR is operated by the California Digital Library (<a href="http://www.cdlib.org/">CDL</a>) on behalf of the international digital curation community, and adheres to the CDL <a href="http://www.cdlib.org/about/privacy.html">privacy policy</a> and its associated baseline practices.  However, the UDFR has a legitimate business need to provide strong provenance information for all contributed information in order that users can make reasonable determinations of information veracity.  Therefore the names and institutional affiliations of content contributors are permanently and publicly made visible through a link on the &quot;History&quot; tab.
 As required by the CDL policy, this permitted exception to the baseline practices is reviewed annually for continued applicability.

</p>