<?php

/**
 * Copyright © 2012 The Regents of the University of California
 *
 * The Unified Digital Format Registry (UDFR) is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<h2>Terms of use</h2>
<p style="text-align:justify">
The UDFR is operated by the California Digital Library (<a href="http://www.cdlib.org/">CDL</a>) on behalf of the international digital curation community.   
Users of the UDFR should recognize that the information managed in the registry was contributed under the terms of various licenses, as indicated in the &quot;History&quot; tab.  
Information from individual contributors is supplied under the <a href="http://creativecommons.org/licenses/by/2.0/">CC-BY</a> license; information from the 
<a href="http://www.nationalarchives.gov.uk/PRONOM/Default.aspx/">PRONOM</a> registry is supplied under the 
<a href="http://www.nationalarchives.gov.uk/doc/open-government-licence/" >OGL</a> license.  
These licenses permit the widest possible use, copying, transmission, adaptation, and commercial exploitation, but also impose an obligation for attribution.  
It is incumbent on UDFR users to comply with this and all other relevant license terms in their own use of this information. 
</br></br>
INFORMATION IS PROVIDED BY THE UDFR AND ITS CONTRIBUTORS &quot;AS IS&quot; AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OF THE UNIVERSITY OF CALIFORNIA, THE CALIFORNIA DIGITAL LIBRARY, OR UDFR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS INFORMATION, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
</p>
