<div align="center">
	<img width=10% height=10% src="<?php echo $this->url ?>extensions/themes/silverblue/images/udfr.gif" alt="UDFR" />
</div>
<div>
	<p style="font-size:14px">The Unified Digital Format Registry project is an open source platform for an online, semantically-enabled registry of significant format representation information.</br>
	The UDFR is an initiative begun in April 2009 to build a single shared formats registry. 
</p>
</div>