<?php

/**
 * Copyright © 2012 The Regents of the University of California
 *
 * The Unified Digital Format Registry (UDFR) is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

?>
<div align="center">
	<img width=10% height=10% src="<?php echo $this->url ?>extensions/themes/silverblue/images/udfr.gif" alt="UDFR" />
</div>
<div>
	<p style="font-size:14px">The Unified Digital Format Registry project is an open source platform for an online, semantically-enabled registry of significant format representation information.</br>
	The UDFR is an initiative begun in April 2009 to build a single shared formats registry. 
</p>
</div>