<?php $odd = false; ?>
<?php if (!empty($this->historyArray)) { ?>
<table class="separated-vertical" id="history-list">
    <thead>
    <!-- history table headers -->
    <tr class="odd">
        <th><?php echo $this->_('select'); ?>          </th>
        <th><?php echo $this->_('ID'); ?>              </th>
        <?php if(!$this->singleResource){?><th><?php echo $this->_('resource'); ?> </th><?php } ?>
        <th><?php echo $this->_('user'); ?>            </th>
        <th><?php echo $this->_('timestamp'); ?>       </th>
        <th><?php echo $this->_('action-type'); ?>     </th>
    </tr>
    </thead>
    <tbody>
    <!-- history table contents -->
    <?php $i = 0; ?>      
    <?php foreach ($this->historyArray as $abschnitt) :?>
    <tr class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?> ">
        <td class="selector">
            <input
                <?php if (!$this->rollbackAllowed) echo 'disabled'; ?> 
                type="radio"
                id="actionid-<?php echo $abschnitt['id']; ?>"
                name="actionid"
                <?php 
                    $chunk = array_chunk($this->idArray,$i++ + 1); 
                    $idString = htmlentities(serialize($chunk[0]));
                ?>
                value="<?php echo $idString; ?>"/>
        </td>
        <td class="enumeration">
            <label for="actionid-<?php echo $abschnitt['id']; ?>"><?php echo $abschnitt['id']; ?></label>
        </td>
        <?php if(!$this->singleResource){?><td><a href="<?php echo $abschnitt['url']; ?>"><?php echo $this->titleHelper->getTitle($abschnitt['resource']); ?></a></td><?php } ?>
        <!--UDFR - Abhi - User Profile task requirement-->
		<td class="user-detail">
		<?php $url= $this->url ; $useruri = $this->userArray[$abschnitt['useruri']]; if($useruri != "Anonymous") { if($useruri != "Admin") {
		echo '<a title="Click to open profile" href="javascript:callme(' . '\'' . $this->userArray[$abschnitt['useruri']]. '\' , \''.$url .  '\''.');">' .$this->userArray[$abschnitt['useruri']].' </a>';
		} else { echo $this->userArray[$abschnitt['useruri']]; } } else { echo $this->userArray[$abschnitt['useruri']]; } ?>
		</td>
        <td>
            <?php $timestamp = date('c', (int) $abschnitt['tstamp']); ?>
            <?php echo OntoWiki_Utils::dateDifference($timestamp) . ' ('.substr($timestamp,0,strlen($timestamp) - 6).')'; ?>
        </td>
        <td class="history-detail"><a><?php echo $this->_('HISTORY_ACTIONTYPE_' . $abschnitt['action_type']); ?></a>
            <div style="display:none;" class="is-processing"><?php echo $abschnitt['id']; ?></div>
        </td>
    </tr>
    <?php endforeach; ?>
                    
    </tbody>
</table>
<?php } ?>

<script type="text/javascript">

    $(document).ready(function() {
        $('#history-list .history-detail').livequery('click', function (event) {

            var node = $(this).children('div');
            if (node.hasClass('is-processing')) {
                var param = node.text();
                node.text('');
                $.get(urlBase + "history/details/id/" + param, function(data){
                        node.html(data);
                        node.removeClass('is-processing');
                    });
            }
            node.toggle();
            event.stopPropagation();
        });
    });
	
	//UDFR - Abhi - User Profile task requirements
	function callme(username, url) {
		var height = $(document).height();
        var width = $(document).width();
		$('#userdetail-popup').remove();
		$('body').append('<div id="back-overlay" class="back-overlay"></div>');
		$('body').append('<div id="userdetail-popup" class="userdetail" ></div>');
		$('body').append('<div id="close-button" style="z-index:1000100; top:190px; left:862px; position:absolute;"><img src="'+url+'extensions/themes/silverblue/images/close_button.png" width="35px" height="35px"alt="X Close X" onclick="close_all()" title="Close"border="0" /></div>');
		$('#userdetail-popup').css("top", 200);
		$('#userdetail-popup').css("left", 473);
		$('#back-overlay').css("height", height);
		$('#back-overlay').css("width", width);
		var model = 'http://www.udfr.org/profile/';
		var query = "SELECT * WHERE {<"+model+username+"> ?p ?o}&default-graph-uri="+model;
  
		// Fires the ajax request
		$.ajax({
			type: "POST",
			url: url + 'sparql?query=' + query,
			cache: false,
			dataType: 'json', 
			success: function(data) {
				$('#userdetail-popup').css("background-image","none");
				if (data && data['results'] && data['results']['bindings']) {
                    var bindings  = data['results']['bindings'];
					var max = bindings.length;
					if (max > 0) {
					for (var i = 0; i < max; i++) {
						if ( bindings[i].p.value == "http://www.udfr.org/profile/userName") {
							$('#userdetail-popup').append('<p><b>Username :  </b> '+bindings[i].o.value+'</p>');
						} 
					} 
					for (var i = 0; i < max; i++) {
						if ( bindings[i].p.value == "http://www.udfr.org/profile/jobTitle") {
							$('#userdetail-popup').append('<p><b>Title &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp:  </b>'+bindings[i].o.value+'</p>');
						}
					}
					for (var i = 0; i < max; i++) {
						if ( bindings[i].p.value == "http://www.udfr.org/profile/orgAffiliation") {
							$('#userdetail-popup').append('<p><b>Affiliation &nbsp:  </b>'+bindings[i].o.value+'</p>');
						}
					}	
					for (var i = 0; i < max; i++) { 
						if ( bindings[i].p.value == "http://www.udfr.org/profile/website") {
							$('#userdetail-popup').append('<p><b>Website &nbsp&nbsp&nbsp&nbsp:  </b> <a onclick=window.open("http://'+bindings[i].o.value+'");>'+bindings[i].o.value+'</a></p>');
						}
					}
					for (var i = 0; i < max; i++) { 
						if (bindings[i].p.value == "http://www.udfr.org/profile/notes") {
							$('#userdetail-popup').append('<p><b>Note &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp :  </b> '+bindings[i].o.value+'</p>');
						}
					}
					$('#userdetail-popup').children('p').css("margin", 10);
					
					} else { 
						$('#userdetail-popup').append('<p> Profile could not find... </p>');
						$('#userdetail-popup').children('p').css("margin", 40);
					}
				}
			}
		});
	}
	function close_all () {
		$('#userdetail-popup').remove();
		$('#back-overlay').remove();
		$('#close-button').remove();
	}
	
</script>
