<?php

/**
 * Copyright © 2012 The Regents of the University of California
 *
 * The Unified Digital Format Registry (UDFR) is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/**
 * OntoWiki application module template
 *
 * @version $Id$
 */

?>

<form method="GET" action="<?php echo $this->actionUrl ?>">
	<?php if ($this->showSearch) : ?>
	<p class="width98">
		<label class="display-block" for="searchtext-input"><?php echo $this->_('Search for Resources') ?></label>
		<input class="text width99 inner-label" type="text" id="searchtext-input" name="searchtext-input" value="<?php echo $this->searchtextinput ?>" />
	</p>
	<?php endif; ?>
	<p>
		<!--label class="display-block">
		    <?php $selected = ($this->modelSelected ? '' : 'checked="checked"') ?>
			<input class="checkbox" type="checkbox" name="allModels" id="allModels" <?php echo $selected ?>/>
			<?php echo $this->_('Search all Knowledge Bases') ?>
		</label-->
		<!-- UDFR- Abhi Hide Virtuoso logo and place udfr logo 
		<?php //if ($this->has('logo')): ?>
		    <img src="<?php //echo $this->logo ?>" style="float:right;vertical-align:bottom" alt="<?php //echo $this->logo_alt ?>" />
		<?php //endif; ?>
		-->
		<img width=15% height=15% src="<?php echo $this->url ?>extensions/themes/silverblue/images/udfr.gif" style="float:right;vertical-align:bottom" alt="UDFR" />
		<!--a class="button submit"><?php echo $this->_('Submit') ?></a-->
	</p>
</form>
